version: '3.8'

services: 
  postgres:
    image: postgres:13
    container_name: novabank_postgres
    environment:
      POSTGRES_USER: CCCTP
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: novabank
    ports: 
      - "5500:5432"
    volumes:
      - postgres_data:/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data: